### ISSUE TITLE
A simple full stack application 

### ISSUE THREAD

**Issue by vivek1996** [hugobots/screencast-ideas#2]
A simple application using any framework preferably angular and node at backend.

**Comment by VhatAmI** [comment]
This would be awesome, especially if it was a ground-up tutorial assuming no prior knowledge. 

I'd imagine it would be a multiple video broadcast 
Video 1 - install the MEAN stack requirements (or another stack? )
Video 2 - run hello world on the stack 
Video 3 - some "must-knows" for the stack/tips and tricks 
Video 4 - more advanced stuff/ summary/ wrap up /additional resources to learn more 

You could repeat this formula for multiple stacks, showing the pros and cons and trade-offs that each tech stack comes with.

**Comment by vivek1996** [comment]
Great.......
